// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_5G_mN9-ObQ6P0N5UQjIX_aZKb9YhQA',
    appId: '1:103223415683:web:7e37873d86fd32c9c29cb6',
    messagingSenderId: '103223415683',
    projectId: 'aferconpay1',
    authDomain: 'aferconpay1.firebaseapp.com',
    storageBucket: 'aferconpay1.firebasestorage.app',
    measurementId: 'G-9RL8WETNQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJH65ODUdDLwEKC1yCnMS-h5KMCxgPDaE',
    appId: '1:103223415683:android:1c65fbd3d72310f4c29cb6',
    messagingSenderId: '103223415683',
    projectId: 'aferconpay1',
    storageBucket: 'aferconpay1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAddOMfgwaJpoBxgtIYW1i4TbR0BdMUTDA',
    appId: '1:103223415683:ios:a9f7ab25991fa228c29cb6',
    messagingSenderId: '103223415683',
    projectId: 'aferconpay1',
    storageBucket: 'aferconpay1.firebasestorage.app',
    androidClientId: '103223415683-bqen6pta6lmmrod3aq33h95niib06bh7.apps.googleusercontent.com',
    iosClientId: '103223415683-61h719n0r3vkfqejgivshc47ksmgjq7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.aferconPay',
  );

}